//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGrade.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Vehicle : global::System.Configuration.ApplicationSettingsBase {
        
        private static Vehicle defaultInstance = ((Vehicle)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Vehicle())));
        
        public static Vehicle Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double setVehicle_antennaHeight {
            get {
                return ((double)(this["setVehicle_antennaHeight"]));
            }
            set {
                this["setVehicle_antennaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double setVehicle_wheelbase {
            get {
                return ((double)(this["setVehicle_wheelbase"]));
            }
            set {
                this["setVehicle_wheelbase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default - ")]
        public string setVehicle_Name {
            get {
                return ((string)(this["setVehicle_Name"]));
            }
            set {
                this["setVehicle_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double setVehicle_goalPointLookAhead {
            get {
                return ((double)(this["setVehicle_goalPointLookAhead"]));
            }
            set {
                this["setVehicle_goalPointLookAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double setVehicle_maxAngularVelocity {
            get {
                return ((double)(this["setVehicle_maxAngularVelocity"]));
            }
            set {
                this["setVehicle_maxAngularVelocity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double setVehicle_maxSteerAngle {
            get {
                return ((double)(this["setVehicle_maxSteerAngle"]));
            }
            set {
                this["setVehicle_maxSteerAngle"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double setVehicle_plowHeight
        {
            get
            {
                return ((double)(this["setVehicle_plowHeight"]));
            }
            set
            {
                this["setVehicle_plowHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double setVehicle_maxDitchCut
        {
            get
            {
                return ((double)(this["setVehicle_maxDitchCut"]));
            }
            set
            {
                this["setVehicle_maxDitchCut"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double setVehicle_maxTileCut
        {
            get
            {
                return ((double)(this["setVehicle_maxTileCut"]));
            }
            set
            {
                this["setVehicle_maxTileCut"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double setVehicle_minTileCover
        {
            get
            {
                return ((double)(this["setVehicle_minTileCover"]));
            }
            set
            {
                this["setVehicle_minTileCover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]

        public double setVehicle_KpGain
        {
            get
            {
                return ((double)(this["setVehicle_KpGain"]));
            }
            set
            {
                this["setVehicle_KpGain"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]

        public double setVehicle_KiGain
        {
            get
            {
                return ((double)(this["setVehicle_KiGain"]));
            }
            set
            {
                this["setVehicle_KiGain"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]

        public double setVehicle_KdGain
        {
            get
            {
                return ((double)(this["setVehicle_KdGain"]));
            }
            set
            {
                this["setVehicle_KdGain"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]


        public double setVehicle_viewDistAboveGnd
        {
            get
            {
                return ((double)(this["setVehicle_viewDistAboveGnd"]));
            }
            set
            {
                this["setVehicle_viewDistAboveGnd"] = value;
            }


        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double setVehicle_viewDistUnderGnd
        {
            get
            {
                return ((double)(this["setVehicle_viewDistUnderGnd"]));
            }
            set
            {
                this["setVehicle_viewDistUnderGnd"] = value;
            }


        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        
        public double setVehicle_toolWidth {
            get {
                return ((double)(this["setVehicle_toolWidth"]));
            }
            set {
                this["setVehicle_toolWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.001")]
        public double setVehicle_minSlope {
            get {
                return ((double)(this["setVehicle_minSlope"]));
            }
            set {
                this["setVehicle_minSlope"] = value;
            }
        }
    }
}
